repos:
- repo: local
  hooks:
    - id: freeze-version
      name: Freeze version
      entry: python -m scripts.git_versioning_callback
      language: system
      stages: [commit-msg]
      verbose: true